language: python
addons:
  sonarcloud:
    token: ${SONAR_TOKEN}
python:
    - "3.6"
install:
    - "pip install pipenv"
    - "pipenv install --dev"
    - "pip install pylint"
script: 
    - pipenv run test
    - pipenv run linter
    - sonar-scanner -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey=blask-project-key -Dsonar.sources=blask/ -Dsonar.organization=zerasul-github -Dsonar.python.coverage.reportPaths=coverage.xml -Dsonar.projectName=blask
after_success:
  coveralls
