language: python
python:
    - "3.6"
install:
    - "pip install -r requirements.txt"
    - "pip install pylint"
script: export PYTHONPATH=$PYTHONPATH:$(pwd) && pytest --cov=Blask --cov-report= && pylint Blask --exit-zero
after_success:
  coveralls
